name = "website"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[vars]
# Environment variables for your Pages Functions
